name: Go Build, Test and Publish Artifacts
on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install package
      run: sudo apt-get -y install wget

    - name: Build
      run: ./build.sh
