name: Go Build, Test and Publish Artifacts
on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install package
      run: sudo apt-get -y install wget

    - name: Build
      run: ./build.sh

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-binaries
        include-hidden-files: true
        path: |
          build/go

  release:
    needs: [build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download linux artefacts
      if: ${{ startsWith(github.event.ref, 'refs/tags/v') }}
      uses: actions/download-artifact@v4
      with:
        name: linux-binaries
        path: dist-linux

    - name: Set VERSION variable from tag
      run: echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')" >> $GITHUB_ENV
    - name: Show VERSION
      run: echo "VERSION=$(VERSION)"

    - name: Create zip archive (linux)
      if: ${{ startsWith(github.event.ref, 'refs/tags/v') }}
      run: cd dist-linux && zip -9 -r go${VERSION}.linux-amd64.zip *

    - name: Publish release
      if: ${{ startsWith(github.event.ref, 'refs/tags/v') }}
      uses: ncipollo/release-action@v1
      with:
        prerelease: true
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        omitPrereleaseDuringUpdate: true
        artifacts: dist-windows/*.zip, dist-linux/*.zip
